site_name: Actimator
site_favicon: img/favicon.ico
pages:

- [index.md, 'What is Actimator?']
- [elements.md, Actimator Game Design Elements]
- [asset.md, Assets]
- [actor.md, Actors]

- [program.md, Actimator Programming Language]
- [events.md, Events]
- [commands.md, Commands]
- [control_flow.md, Control Flow]

- [scene.md, Scene]
- [physics.md, Physics in Actimator]
- [image.md, Scene Images]
- [layers.md, Layers]
- [audio.md, Audio Management]

- [learn.md, Learn Actimator]
- [teach.md, Teach Actimator]

theme: readthedocs

site_dir: ../server/public/docs